# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as d
print(d.arange(2,50,3)) #start,stop,stepsize(difference)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [14]:
l1=[] 
l2=[]

print("Elements of first list:")
print(" ")
i=1
while(i<=5):
    a=int(input("Enter the "+str(i)+" element: "))
    l1.append(a)
    i=i+1
print(l1)
print(" ")
print("Elements of second list:")
print(" ")
j=1
while(j<=5):
    b=int(input("Enter the "+str(j)+" element: "))
    l2.append(b)
    j=j+1
print(l2)
print(" ")
print("Conversion of list to numpy array")

# converting list to array
na = d.array(l1)
nb = d.array(l2)
print("Conversion of first list to numpy array: ",na)    
print("Conversion of second list to numpy array: ",nb)

c=d.concatenate((na,nb))
print("The concatenation of the two numpy array is: ",c)
print(" ")
s=d.sort(c)
print("The sorted numpy array is: ",s)

Elements of first list:
 
Enter the 1 element: 22
Enter the 2 element: 34
Enter the 3 element: 56
Enter the 4 element: 87
Enter the 5 element: 12
[22, 34, 56, 87, 12]
 
Elements of second list:
 
Enter the 1 element: 45
Enter the 2 element: 1
Enter the 3 element: 5
Enter the 4 element: 9
Enter the 5 element: 14
[45, 1, 5, 9, 14]
 
Conversion of list to numpy array
Conversion of first list to numpy array:  [22 34 56 87 12]
Conversion of second list to numpy array:  [45  1  5  9 14]
The concatenation of the two numpy array is:  [22 34 56 87 12 45  1  5  9 14]
 
The sorted numpy array is:  [ 1  5  9 12 14 22 34 45 56 87]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [20]:
import numpy as n
a=n.array([1,2,3,4,5,])
print("The numpy array a: ",a)
print("The dimension of the numpy array a is: ",d.shape(a))
a1=n.size(a)# size is no. of elements in an array
print("The size of the numpy array a is: ",a1)



print(" ")
b=n.array([[9,8,7],[6,5,4]])
print("The numpy array a: ",b)
print("The dimension of the numpy array a is: ",d.shape(b))
b1=n.size(b)
print("The size of the numpy array a is: ",b1)

The numpy array a:  [1 2 3 4 5]
The dimension of the numpy array a is:  (5,)
The size of the numpy array a is:  5
 
The numpy array a:  [[9 8 7]
 [6 5 4]]
The dimension of the numpy array a is:  (2, 3)
The size of the numpy array a is:  6


# Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [55]:
import numpy as np
# creating a 1d array
arr = np.arange(10)
print("\nShape of Array :",arr.shape)

# converting using newaxis in row wise
row_arr = arr[np.newaxis, :]
print("\nShape of 2d Array in row major :",row_arr.shape)

# converting using newaxis in column wise
col_arr = arr[:, np.newaxis]
print("\nShape of 2d Array in column major :",col_arr.shape)


Shape of Array : (10,)

Shape of 2d Array in row major : (1, 10)

Shape of 2d Array in column major : (10, 1)


In [56]:
# importing numpy
import numpy as np

# creating a 1d array
arr = np.arange(10)
print("\nShape of Array :",arr.shape)

# converting using newaxis in row wise
row_arr = np.expand_dims(arr, axis=0)
print("\nShape of 2d Array in row major :",row_arr.shape)

# converting using newaxis in column wise
col_arr = np.expand_dims(arr, axis=1)
print("\nShape of 2d Array in column major :",col_arr.shape)


Shape of Array : (10,)

Shape of 2d Array in row major : (1, 10)

Shape of 2d Array in column major : (10, 1)


# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [57]:
import numpy as np

# creating a array with square values
arr_1 = np.square([1, 2, 3, 4, 5])
arr_2 = np.square([6, 7, 8, 9, 10])

# stacking and printing the value
print("\nHorizontal Append :", np.hstack((arr_1, arr_2)))
print("\nVertical Append :", np.vstack((arr_1, arr_2)))


Horizontal Append : [  1   4   9  16  25  36  49  64  81 100]

Vertical Append : [[  1   4   9  16  25]
 [ 36  49  64  81 100]]


# Questions 6:
How to get unique items and counts of unique items?

In [59]:
# importing numpy
import numpy as np

# creating a array 
arr_1 = np.array([1, 4, 9, 16, 25, 1, 4, 2, 3, 2, 5, 6, 5, 7, 8, 10])

# getting unique charater and its count
unique, counts = np.unique(arr_1, return_counts=True)


# making a 
arr = np.asarray((unique, counts)).T

print(arr)

[[ 1  2]
 [ 2  2]
 [ 3  1]
 [ 4  2]
 [ 5  2]
 [ 6  1]
 [ 7  1]
 [ 8  1]
 [ 9  1]
 [10  1]
 [16  1]
 [25  1]]
